language: generic
sudo: required
services:
  - docker
before_script:
  - docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
script:
  - .travis/build.sh
after_success:
  - |
    if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      docker run infolinks/github-release:${TRAVIS_COMMIT} \
          --token="${GITHUB_ACCESS_TOKEN}" \
          --repo="${TRAVIS_REPO_SLUG}" \
          --commit="${TRAVIS_COMMIT}"
    fi
